In [ ]:
import numpy as np

In [ ]:
liste = [1, 2, 3, 4, 5, 6, 7, 8]
liste

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
liste2 = np.array( [ (1,2,3,4), (5,6,7,8), (9,10,11,12)] )
liste2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(liste2.shape)
print(liste2.size)

(3, 4)
12


In [ ]:
liste3 = np.arange(10)
liste3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
liste3 = liste3.reshape(2,5)
liste3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
random_matris = np.random.randint(20,70,15)
random_matris = random_matris.reshape(5,3)
random_matris

array([[34, 29, 56],
       [30, 62, 47],
       [33, 26, 41],
       [66, 22, 21],
       [21, 39, 32]])

In [ ]:
print("Aritmetik:\t", np.mean(random_matris))
print("Medyan:\t\t", np.median(random_matris))
print("Varyans:\t", np.var(random_matris))
print("Standat Sapma:\t", np.std(random_matris))

Aritmetik:	 37.266666666666666
Medyan:		 33.0
Varyans:	 197.7955555555555
Standat Sapma:	 14.063980786233872
